export const frontendSpeakers = [
  {
    name: "Ben Hong",
    pic: "ben.jpeg",
    twitter: "bencodezen",
    bio: "@vuejs core team & senior staff dx engineer @netlify",
    talk: "Third Time's the Charm: Taking Another Look at Vue 3",
  },
  {
    name: "Charlie Gerard",
    pic: "charlie.jpeg",
    twitter: "devdevcharlie",
    bio: "Senior developer advocate  @Stripe",
    talk: "Simple JStures can go a long way",
  },
  {
    name: "Natalia Tepluhina",
    pic: "natalia.jpeg",
    twitter: "N_Tepluhina",
    bio: "@vuejs core team & Staff Frontend Engineer @gitlab",
    talk: "Local state and server cache: finding a balance",
  },
  {
    name: "Jessica Janiuk",
    pic: "jessica.jpeg",
    twitter: "ThePunderWoman",
    bio: "Angular Team @Google",
  },
  {
    name: "Cassidy Williams",
    pic: "cassidy.jpeg",
    twitter: "cassidoo",
    bio: "Head of DX and Education at @remote",
    talk: "MC",
  },
  {
    name: "Dan Abramov",
    pic: "dan.jpeg",
    twitter: "dan_abramov",
    bio: "React team at @Meta",
    talk: "Q&A",
    qa: true,
  },
  {
    name: "Tomasz Łakomy",
    pic: "tomasz.jpeg",
    twitter: "tlakomy",
    bio: "Frontend Engineer at @Stedi",
    turtle: true,
  },
  {
    name: "Volodymyr Agafonkin",
    twitter: "mourner",
    pic: "vladimir.jpeg",
    bio: "Engineer at @Mapbox, creator of @LeafletJS, algorithms geek, rock musician",
    talk: "Solving everyday problems with data visualization",
  },
  {
    name: "Addy Osmani",
    twitter: "addyosmani",
    pic: "addy.jpeg",
    bio: "Engineering manager working on @GoogleChrome",
  },
]

export const backendSpeakers = [
  {
    name: "Lilly Chen",
    pic: "lilly.jpeg",
    twitter: "lillydoingecon",
    bio: "Founder at @ContendaCo",
  },
  {
    name: "Sandi Metz",
    pic: "sandi.jpeg",
    twitter: "sandimetz",
    bio: "Cyclist, Rubyist, author",
  },
  {
    name: "Aaron Patterson",
    pic: "aaron.jpeg",
    twitter: "tenderlove",
    bio: "Human at @Shopify",
  },
  {
    name: "Saša Jurić",
    pic: "sasa.jpeg",
    twitter: "sasajuric",
    bio: "Elixir mentor, author of Elixir in Action",
    talk: "Fireside chat 🔥",
  },
  {
    name: "José Valim",
    pic: "jose.jpeg",
    twitter: "josevalim",
    bio: "Chief Adoption Officer at @dashbit. Creator of @elixirlang.",
  },
  {
    name: "Andreas Klinger",
    pic: "andreas.jpeg",
    twitter: "andreasklinger",
    bio: "CTO @beondeck",
    talk: "Fireside chat 🔥",
  },
  {
    name: "Tetiana",
    pic: "tetiana.jpeg",
    twitter: "Tetiana12345678",
    bio: "Programmer, in love with Elixir-lang, proud mum, creator of @elixircards and @gitcards",
  },
  {
    name: "Vittoria Bitton",
    pic: "vittoria.jpeg",
    twitter: "vittoria_bitton",
    bio: "Senior Backend Engineer at @remote",
  },
  {
    name: "Anjana Vakil",
    pic: "anjana.jpeg",
    twitter: "AnjanaVakil",
    bio: " Senior Developer Advocate @HasuraHQ",
    talk: "Opening Doors with Open Source",
  },
  {
    name: "Tobi Pfeiffer ",
    pic: "tobi.jpg",
    twitter: "PragTob",
    bio: "Staff Engineer @remote",
    talk: "MC",
  },
]
